### ISSUE TITLE
How well do you know the legislators?

### ISSUE THREAD

**Issue by baldwmic** [kevc/govt#1]
“Know thy self, know thy enemy. A thousand battles, a thousand victories.”

― Sun Tzu, The Art of War

**Comment by kevc** [comment]
@baldwmic 🙌  😆 🤣

**Comment by baldwmic** [comment]
@kevc Sun tells us we should close this issue.

```
“The greatest victory is that which requires no battle.” 
― Sun Tzu, The Art of War
```
